default: &default
    adapter: mysql2
    encoding: utf8mb4
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username: <%= ENV['DB_USERNAME'] %>
    password: <%= ENV['DB_PASSWORD'] %>
    host: <%= ENV['DB_HOST'] %>
    port: <%= ENV['DB_RAILS_PORT_INT'] %>

development:
    <<: *default
    database: pokemon_development

test:
    <<: *default
    database: pokemon_test

production:
    <<: *default
    database: pokemon_production